### ISSUE TITLE
エラーの変化を報酬に加えることに関して

### ISSUE THREAD

**Issue by yasuohayashibara** [jsupratman13/human_robot_interaction#2]
こちら要検討と思います．

https://github.com/jsupratman13/human_interaction_robot/blob/a7c8bbfa372b108fba0f61969be69988aca45c5b/hir_learning/scripts/environment.py#L56-L60

あとで議論しましょう．

**Comment by yasuohayashibara** [comment]
あと，エラーの絶対値が報酬になっているかを再度確認してください．

**Comment by jsupratman13** [comment]
実機では別をファイルを使用しています。
environment.pyではなくreal_environment.pyです。

実際の報酬

reward = sigma (no load joint - current joint)^2


コードの報酬
https://github.com/jsupratman13/human_interaction_robot/blob/a7c8bbfa372b108fba0f61969be69988aca45c5b/hir_learning/scripts/real_environment.py#L150

**Comment by yasuohayashibara** [comment]
確認しました．
issueを閉じます．
