### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yasuohayashibara** [jsupratman13/human_robot_interaction#3]
iだと思います．

https://github.com/jsupratman13/human_interaction_robot/blob/a7c8bbfa372b108fba0f61969be69988aca45c5b/hir_learning/scripts/real_environment.py#L73

**Comment by jsupratman13** [comment]
@yasuohayashibara 
どうもありごうとうございます！
修正しました。
https://github.com/jsupratman13/human_interaction_robot/blob/785a4aab283e8aae9dc98221adb6ff1de0be6a6c/hir_learning/scripts/real_environment.py#L73
https://github.com/jsupratman13/human_interaction_robot/blob/785a4aab283e8aae9dc98221adb6ff1de0be6a6c/hir_learning/scripts/real_environment.py#L74

**Comment by yasuohayashibara** [comment]
解決したのでissueを閉じます．
